# Generated by Django 4.0.6 on 2022-08-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='post.post'),
        ),
    ]
